const students = [
  {
    id: 1,
    name: 'Nguyễn Minh Anh',
    grade: 'Lớp 5',
    bus: 'Xe số 12',
    route: 'Tuyến A',
    pickup: '123 Đường Lê Lợi',
    dropoff: 'Trường Tiểu học Lý Thường Kiệt',
    parent: 'Trần Thị Hoa',
    phone: '+1 (555) 111-2222',
    present: true,
  },
  {
    id: 2,
    name: 'Lê Gia Bảo',
    grade: 'Lớp 4',
    bus: 'Xe số 07',
    route: 'Tuyến B',
    pickup: '456 Đường Nguyễn Huệ',
    dropoff: 'Trường THCS Nguyễn Gia Thiều',
    parent: 'Lê Văn Dũng',
    phone: '+84 812 346 789',
    present: true,
  },
  {
    id: 3,
    name: 'Phạm Ngọc Ánh',
    grade: 'Lớp 3',
    bus: 'Xe số 12',
    route: 'Tuyến A',
    pickup: '789 Đường Trần Hưng Đạo',
    dropoff: 'Trường Tiểu học Nguyễn Du',
    parent: 'Phạm Quang Huy',
    phone: '+84 812 123 009',
    present: false,
  },
  {
    id: 4,
    name: 'Trần Quốc Khánh',
    grade: 'Lớp 2',
    bus: 'Xe số 24',
    route: 'Tuyến D',
    pickup: '321 Đường Phan Đình Phùng',
    dropoff: 'Trường THCS Chu Văn An',
    parent: 'Trần Thị Mai',
    phone: '+84 812 123 452',
    present: true,
  },
  {
    id: 5,
    name: 'Vũ Thảo Nhi',
    grade: 'Lớp 1',
    bus: 'Xe số 07',
    route: 'Tuyến B',
    pickup: '654 Đường Hai Bà Trưng',
    dropoff: 'Trường THCS Lý Tự Trọng',
    parent: 'Vũ Đức Long',
    phone: '++84 542 123 122',
    present: true,
  },
  {
    id: 6,
    name: 'Đỗ Hoàng Nam',
    grade: 'Lớp 6',
    bus: 'Xe số 19',
    route: 'Tuyến C',
    pickup: '987 Đường Nguyễn Trãi',
    dropoff: 'Trường Tiểu học Trần Quốc Toản',
    parent: 'Đỗ Thu Hà',
    phone: '+84 542 234 001',
    present: true,
  },
  {
    id: 7,
    name: 'Ngô Bảo Châu',
    grade: 'Lớp 5',
    bus: 'Xe số 05',
    route: 'Tuyến A',
    pickup: '147 Đường Võ Thị Sáu',
    dropoff: 'Trường Tiểu học Đinh Tiên Hoàng',
    parent: 'Ngô Thị Lan',
    phone: '+84 901 234 122',
    present: false,
  },
  {
    id: 8,
    name: 'Hoàng Minh Tuấn',
    grade: 'Lớp 4',
    bus: 'Xe số 24',
    route: 'Tuyến D',
    pickup: '258 Đường Điện Biên Phủ',
    dropoff: 'Trường THCS Hồng Bàng',
    parent: 'Hoàng Anh Tuấn',
    phone: '+84 799 232 463',
    present: true,
  },
];

export { students };
