@startuml
title Create Assign - Sequence Diagram

actor "Quản lý" as ql
participant "~~:AssignController~~" as co
participant "~~:Routes~~" as ro
participant "~~:Driver~~" as dr
participant "~~:Bus~~" as bu

ql --> co : addAssign(assign)
co --> ql : AssignRecord[]
co --> dr : getDrivers()
dr --> co : DriverRecord[]
co --> ro : getRoutes()
ro --> co : RouteRecord[]
co --> bu : getBus()
bu --> co : BusRecord[]