@startuml
' Class
Class TaiXe {
    - maTaiXe
    - hoTen
    - soDienThoai
    - email
    - diaChi
    - soGiayPhep
    - ngayHetHanGiayPhep
    - ngaySinh
    - trangThai

    +capNhatThongTinTaiXe(hoTenMoi, soDienThoaiMoi, emailMoi, diaChiMoi)
    +dangKyLichLamViec(maLichLamViec)
    +capNhatTrangThai(trangThaiMoi)
}

Class PhuHuynh {
    - maPhuHuynh
    - hoTen
    - soDienThoai
    - email
    - diaChi
    - trangThai

    +capNhatThongTinLienHe(soDienThoaiMoi, emailMoi)
    +nhanThongBao(noiDung)
    +xacNhanTinhTrangHocSinh(maHocSinh, trangThai)
}

Class HocSinh {
    - maHocSinh
    - hoTen
    - ngaySinh
    - gioiTinh
    - lopHoc
    - truongHoc
    - soDienThoaiLienHe
    - trangThai

    +capNhatThongTinLienHe(soDienThoaiMoi)
    +dangKyDanhSachDon(maDanhSach)
    +capNhatTrangThai(trangThaiMoi)
}

Class LichLamViec {
    - maLichLamViec
    - tenLichLamViec
    - ngayLamViec
    - caLamViec
    - gioBatDau
    - gioKetThuc
    - ghiChu
    - trangThai

    +capNhatKhungGio(gioBatDauMoi, gioKetThucMoi)
    +themCongViec(ghiChuMoi)
    +phanCongTaiXe(maTaiXe)
}

Class DanhSachDon {
    - maDanhSach
    - tenDanhSach
    - moTa
    - ngayTao
    - nguoiTao
    - trangThai

    +themHocSinh(maHocSinh)
    +xoaHocSinh(maHocSinh)
    +layDanhSachHocSinh()
}

Abstract LichTrinh {
    - maLichTrinh
    - tenLichTrinh
    - thoiGianDi
    - thoiGianDen
    - ngayApDung
    - trangThai

    +capNhatThoiGian(thoiGianDiMoi, thoiGianDenMoi)
    +themDiaDiem(maDiaDiem)
    +tinhTongThoiGian()
}

Class LichTrinhXe {
    - maLichTrinhXe
    - loaiLichTrinh
    - tuyenDuong
    - quangDuong
    - chuKyLapLai
    - ghiChu

    +capNhatQuangDuong(quangDuongMoi)
    +datChuKyLapLai(chuKyMoi)
    +capNhatGhiChu(ghiChuMoi)
}

Class LichTrinhHocSinh {
    - maLichTrinhHocSinh
    - tenTuyen
    - diemDon
    - diemTra
    - thoiGianChoToiDa
    - ghiChu

    +themHocSinh(maHocSinh)
    +capNhatDiemDon(diemDonMoi, diemTraMoi)
    +capNhatThoiGianCho(thoiGianChoMoi)
}

Class Xe {
    - bienSoXe
    - loaiXe
    - sucChua
    - hangXe
    - namSanXuat
    - mauSac
    - trangThaiXe

    +capNhatTrangThaiXe(trangThaiMoi)
    +dangKyBaoDuong(ngayBaoDuong)
    +kiemTraKhaDung()
}

Class PhanCongXe {
    - maTaiXe
    - bienSoXe
    - ngayPhanCong
    - trangThai
    - ghiChu

    +phanBoTaiXe(maTaiXe, maLichTrinh)
    +capNhatCaLamViec(caLamViecMoi)
    +huyPhanCong()
}

Abstract Tracking {
    - hienDien
    - thoiGianCapNhat
    - kinhDo
    - viDo
    - ghiChu

    +capNhatViTri(kinhDoMoi, viDoMoi)
    +capNhatTrangThaiTheoDoi(trangThaiMoi)
    +layBanGhiGanNhat()
}

Class TrackingTaiXe {
    - maTrackingTaiXe
    - maTaiXe
    - trangThaiTaiXe

    +capNhatTrangThaiTaiXe(trangThaiMoi)
    +layThongTinTaiXe()
    +ghiChuTheoDoi(ghiChuMoi)
}

Class TrackingHocSinh {
    - maTrackingHocSinh
    - maHocSinh
    - trangThaiHocSinh

    +capNhatTrangThaiHocSinh(trangThaiMoi)
    +layThongTinHocSinh()
    +ghiChuTheoDoi(ghiChuMoi)
}

Class LichDonHocSinh {
    - maHocSinh
    - maLichTrinh
    - thoiGianDon
    - thoiGianTra
    - trangThaiDon
    - ghiChu

    +xacNhanDon(maHocSinh)
    +xacNhanTra(maHocSinh)
    +capNhatTrangThaiDon(trangThaiMoi)
}

Class DiaDiem {
    - maDiaDiem
    - tenDiaDiem
    - diaChi
    - kinhDo
    - viDo
    - loaiDiaDiem

    +capNhatToaDo(kinhDoMoi, viDoMoi)
    +capNhatLoaiDiaDiem(loaiMoi)
    +layThongTinDiaDiem()
}

Class TaiXeDiaDiem {
    - maTaiXe
    - maDiaDiem
    - thoiGianDen
    - thoiGianRoi
    - trangThai
    - ghiChu

    +ghiNhanDen(thoiGianDenMoi)
    +ghiNhanRoi(thoiGianRoiMoi)
    +capNhatTrangThai(trangThaiMoi)
}

Class DiaDiemLichTrinh {
    - maDiaDiem
    - maLichTrinh
    - thoiGianDuKien
    - ghiChu

    +sapXepThuTu(thuTu)
    +capNhatThoiGianDuKien(thoiGianMoi)
    +layThongTinDiemDung()
}

' Association

TaiXe"0..*" -- "0..1"LichLamViec : Chua <
LichLamViec "1" o-- "0..*" PhanCongXe : Gom >

LichTrinh <|- LichTrinhXe
LichTrinh <|-- LichTrinhHocSinh

HocSinh"0..*" -- "0..*"LichTrinh : Chua <
DanhSachDon "1" o-- "0..*" HocSinh : Chua >

Xe"0..*" -- "0..*"TaiXe : Lai <
(Xe, TaiXe) . PhanCongXe

PhuHuynh"1..1" -- "1..*"HocSinh : Co >

Tracking <|- TrackingTaiXe
Tracking <|-- TrackingHocSinh
Tracking"1..1" -- "0..*"TaiXe : theo doi >
Tracking"1..1" -- "0..*"HocSinh : theo doi >

(HocSinh, LichTrinh) . LichDonHocSinh

HocSinh"0..*" --- "1..1"DiaDiem : Den >
TaiXe"0..*" -- "1..*"DiaDiem : Den >
(DiaDiem, TaiXe) . TaiXeDiaDiem

LichTrinh "1" o-- "0..*" DiaDiem : Di qua >
(LichTrinh, DiaDiem) . DiaDiemLichTrinh
@enduml
