@startuml
' Class
Class TaiXe {
    - maTaiXe
    - hoTen
    - soDienThoai
    - email
    - diaChi
    - soGiayPhep
    - ngayHetHanGiayPhep
    - ngaySinh
    - trangThai
}

Class PhuHuynh {
    - maPhuHuynh
    - hoTen
    - soDienThoai
    - email
    - diaChi
    - trangThai
}

Class HocSinh {
    - maHocSinh
    - hoTen
    - ngaySinh
    - gioiTinh
    - lopHoc
    - truongHoc
    - soDienThoaiLienHe
    - trangThai
}

Class LichLamViec {
    - maLichLamViec
    - tenLichLamViec
    - ngayLamViec
    - caLamViec
    - gioBatDau
    - gioKetThuc
    - ghiChu
    - trangThai
}

Class DanhSachDon {
    - maDanhSach
    - tenDanhSach
    - moTa
    - ngayTao
    - nguoiTao
    - trangThai
}

Abstract LichTrinh {
    - maLichTrinh
    - tenLichTrinh
    - thoiGianDi
    - thoiGianDen
    - ngayApDung
    - trangThai
}

Class LichTrinhXe {
    - maLichTrinhXe
    - loaiLichTrinh
    - tuyenDuong
    - quangDuong
    - chuKyLapLai
    - ghiChu
}

Class LichTrinhHocSinh {
    - maLichTrinhHocSinh
    - tenTuyen
    - diemDon
    - diemTra
    - thoiGianChoToiDa
    - ghiChu
}

Class Xe {
    - bienSoXe
    - loaiXe
    - sucChua
    - hangXe
    - namSanXuat
    - mauSac
    - trangThaiXe
}

Class PhanCongXe {
    - maTaiXe
    - bienSoXe
    - ngayPhanCong
    - trangThai
    - ghiChu
}

Abstract Tracking {
    - hienDien
    - thoiGianCapNhat
    - kinhDo
    - viDo
    - ghiChu
}

Class TrackingTaiXe {
    - maTrackingTaiXe
    - maTaiXe
    - trangThaiTaiXe
}

Class TrackingHocSinh {
    - maTrackingHocSinh
    - maHocSinh
    - trangThaiHocSinh
}

Class LichDonHocSinh {
    - maHocSinh
    - maLichTrinh
    - thoiGianDon
    - thoiGianTra
    - trangThaiDon
    - ghiChu
}

Class DiaDiem {
    - maDiaDiem
    - tenDiaDiem
    - diaChi
    - kinhDo
    - viDo
    - loaiDiaDiem
}

Class TaiXeDiaDiem {
    - maTaiXe
    - maDiaDiem
    - thoiGianDen
    - thoiGianRoi
    - trangThai
    - ghiChu
}

Class DiaDiemLichTrinh {
    - maDiaDiem
    - maLichTrinh
    - thoiGianDuKien
    - ghiChu
}

' Association

TaiXe"0..*" -- "0..1"LichLamViec : Chua <
LichLamViec "1" o-- "0..*" PhanCongXe : Gom >

LichTrinh <|- LichTrinhXe
LichTrinh <|-- LichTrinhHocSinh

HocSinh"0..*" -- "0..*"LichTrinh : Chua <
DanhSachDon "1" o-- "0..*" HocSinh : Chua >

Xe"0..*" -- "0..*"TaiXe : Lai <
(Xe, TaiXe) . PhanCongXe

PhuHuynh"1..1" -- "1..*"HocSinh : Co >

Tracking <|- TrackingTaiXe
Tracking <|-- TrackingHocSinh
Tracking"1..1" -- "0..*"TaiXe : theo doi >
Tracking"1..1" -- "0..*"HocSinh : theo doi >

(HocSinh, LichTrinh) . LichDonHocSinh

HocSinh"0..*" --- "1..1"DiaDiem : Den >
TaiXe"0..*" -- "1..*"DiaDiem : Den >
(DiaDiem, TaiXe) . TaiXeDiaDiem

LichTrinh "1" o-- "0..*" DiaDiem : Di qua >
(LichTrinh, DiaDiem) . DiaDiemLichTrinh
@enduml
