@startuml
title Assign Management - Sequence Diagram

actor "Quản lý" as ql
participant "~~:AssignController~~" as co
participant "~~:Routes~~" as ro
participant "~~:Driver~~" as dr
participant "~~:Bus~~" as bu

== Lấy dữ liệu để tạo form ==
ql -> co : getRoutes()
activate co
co -> ro : getRoutes()
activate ro
ro --> co : RouteRecord[]
deactivate ro
co --> ql : RouteRecord[]
deactivate co

ql -> co : getDrivers()
activate co
co -> dr : getDrivers()
activate dr
dr --> co : DriverRecord[]
deactivate dr
co --> ql : DriverRecord[]
deactivate co

ql -> co : getBus()
activate co
co -> bu : getBus()
activate bu
bu --> co : BusRecord[]
deactivate bu
co --> ql : BusRecord[]
deactivate co

== Tạo Assignment ==
ql -> co : addAssign(assign: AssignRecord)
activate co
co -> co : getAssignById(assign.id)
activate co
co --> co : AssignRecord | undefined
deactivate co

alt [Assign với id đã tồn tại]
    co --> ql : Error: "Route with id already exists"
else [Assign hợp lệ]
    co -> co : assignments.push(assign)
    co --> ql : AssignRecord
end
deactivate co

== Chỉnh sửa Assignment ==
ql -> co : getAssignById(id: number)
activate co
co -> co : assignments.find(id)
co --> ql : AssignRecord | undefined
deactivate co

ql -> co : editAssign(id: number, updatedAssign: Partial<AssignRecord>)
activate co
co -> co : assignments.findIndex(id)
activate co
co --> co : number (index)
deactivate co

alt [Phân công không tồn tại]
    co --> ql : Error: "Assignment with id {id} does not exist"
else [Phân công tồn tại]
    co -> co : assignments[index] = {...assignments[index], ...updatedAssign, id}
    co --> ql : AssignRecord
end
deactivate co

== Xóa Assignment ==
ql -> co : removeAssign(id: number)
activate co
co -> co : assignments.findIndex(id)
activate co
co --> co : number (index)
deactivate co

alt [Phân công không tồn tại]
    co --> ql : Error: "Assignment with id {id} does not exist"
else [Phân công tồn tại]
    co -> co : assignments.splice(index, 1)
    co --> ql : void
end
deactivate co

@enduml