@startuml
skinparam packageStyle rectangle
left to right direction

actor "Quản lý" as act

rectangle "Quản lý học sinh" {
    usecase "Thêm học sinh" as Add
    usecase "Sửa học sinh" as Edit
    usecase "Xóa học sinh" as Delete

    act -- Add
    act -- Edit
    act -- Delete
}
@enduml