@startuml
title QLHS first cut class diagram - Add student

class "Add Student" {
    + createStudent(studentName, className, address, ParentName, ParentPhone, studySchedule, routeCode, busCode, assignmentSchedule)
}
class "Student" {
    studentId: String {Key}
    studentName: String
    className: String
    address: String
    studySchedule: Date
    + createStudentInfo(studentName, className, address, studySchedule): Student
    + linkParent(ParentName, ParentPhone)
}
class "Parent" {
    studentId: String {Key}
    ParentName: String
    ParentPhone: String
    + linkParent(ParentName, ParentPhone): Parent
}
class "Route Assignment" {
    routeCode: String
    busCode: String
    assignmentSchedule: Date
    + assignRoute(routeCode, busCode, assignmentSchedule): Route Assignment
}
' Associations
"Add Student" --> "Student"
"Student" --> "Parent"
"Add Student" --> "Route Assignment"
@enduml
