@startuml
title Quản lý học sinh - Thêm học sinh

actor "Quản lý" as QL 
participant "~~:AddStudent~~" as THEMHS 
participant "~~:Student~~" as HS
participant "~~:Parent~~" as PH 
participant "~~:Assign~~" as PC

QL -> THEMHS: createHS(studentName, className, address, parentName, parentPhone, studySchedule, routeCode, busCode, assignmentSchedule)
THEMHS -> HS: createHSinfo(studentName, className, address, studySchedule)
HS -> PH: linkPH(parentName, parentPhone)
PH --> HS: (parentName, parentPhone)
HS --> THEMHS: (studentName, className, address, studySchedule, parentName, parentPhone)
THEMHS -> PC: assignRoute(routeCode, busCode, assignmentSchedule)
PC --> THEMHS: (routeCode, busCode, assignmentSchedule)
THEMHS --> QL: (studentName, className, address, studySchedule, parentName, parentPhone, routeCode, busCode, assignmentSchedule)
@enduml